// SPDX-License-Identifier: GPL-2.0-only

package ops

import (
	"oblikovati.org/kernel/geom"
	"oblikovati.org/kernel/topo"
	"oblikovati.org/math"
)

// T-N7.0 (n7-corner-seam-architecture.md, ADR-1): the ANTICORRUPTION LAYER between the curved-arm weld
// feature (System A) and the RailLoop/CornerBlendProvider engine (System B). extractCurvedCorner turns a
// solved cornerWeld into the RailLoop the engine fills, so System A owns NO fill algorithm and the
// engine stays topo-free (it receives only a RailLoop, never a cornerWeld/armSetback/topo.Face). It is
// the curved-lineage counterpart of the planar extractTrihedral, and finishes the strangler that
// spherePatchFace/appendSetbackPatchFaces already landed for the planar/setback paths.

// extractCurvedCorner builds the corner RailLoop for the octant (3-valence) path: one Side per arm whose
// Curve is that arm's setback great-arc (curvedSetbackRail), Adjacent is the arm surface, and Cont is G1
// — three concentric equal-r arcs the analytic-sphere tier recognizes. The Sides are ordered head-to-tail
// (reusing chainSetbackArcs, the SAME byte-for-byte ordering curvedSphereFace's loop uses, mirroring how
// extractTrihedral reuses chainArcs) so RailLoop.Closed(res.Weld()·r) holds. Provenance is the empty
// lineage — the corner is generated by the trihedral VERTEX, not one edge. ok=false if any rail declines
// or the loop does not close, so curvedWeldFaces falls back to curvedSphereFace (do-no-harm). The N7 4th
// (wall-contact) rail is Task 3; this task wires the octant only. Example:
//
//	loop, ok := extractCurvedCorner(w, arms, res); if ok { patch, ok := resolveBlend(loop, res) }
func extractCurvedCorner(w cornerWeld, arms []edgeFillet, res Resolution) (RailLoop, bool) {
	segs, ok := chainSetbackArcs(w) // ordered/oriented head-to-tail — the byte-path ordering
	if !ok {
		return RailLoop{}, false
	}
	tol := res.Weld() * w.radius
	sides, ok := setbackSides(w, arms, segs, tol)
	if !ok {
		return RailLoop{}, false
	}
	loop := RailLoop{Sides: sides, Provenance: topo.Lineage{}}
	if !loop.Closed(tol) {
		return RailLoop{}, false // rails do not form a single closed cycle within the model weld
	}
	return loop, true
}

// setbackSides turns the ordered setback arcs into RailLoop Sides, re-attaching each arc's arm surface as
// Adjacent (Cont=G1). chainSetbackArcs orders/orients the arcs but drops the arm association the Side needs,
// so each ordered arc is matched back to its arm by its two host-tangent points (each arm owns a distinct
// tangent-point pair). Declines if an ordered seg is not an analytic Arc3d or matches no arm.
func setbackSides(w cornerWeld, arms []edgeFillet, segs []endSeg, tol float64) ([]Side, bool) {
	sides := make([]Side, 0, len(segs))
	for _, s := range segs {
		arc, ok := s.curve.(geom.Arc3d)
		if !ok {
			return nil, false // a non-analytic ordered rail is not the sphere-octant path
		}
		i := armIndexForRail(w, s, tol)
		if i < 0 {
			return nil, false // an ordered rail matched no arm's tangent-point pair (mis-ordered)
		}
		sides = append(sides, Side{Curve: arc, Adjacent: arms[i].armSurface, Cont: G1})
	}
	return sides, true
}

// armIndexForRail returns the index (into w.arms and the index-aligned arms) of the arm whose setback
// rail shares seg's two endpoints in either orientation, or −1 if none. arms[i] ↔ w.arms[i] by index
// (solveCurvedCorner preserves the input order), so the returned index selects arms[i].armSurface.
func armIndexForRail(w cornerWeld, seg endSeg, tol float64) int {
	for i, a := range w.arms {
		t0 := endpointOf(w.center, w.radius, a.railDir0)
		t1 := endpointOf(w.center, w.radius, a.railDir1)
		if endpointsCoincide(seg.from, seg.to, t0, t1, tol) {
			return i
		}
	}
	return -1
}

// endpointsCoincide reports whether the unordered pair {a0,a1} equals {b0,b1} within tol.
func endpointsCoincide(a0, a1, b0, b1 math.Point3, tol float64) bool {
	fwd := float64(a0.DistanceTo(b0)) <= tol && float64(a1.DistanceTo(b1)) <= tol
	rev := float64(a0.DistanceTo(b1)) <= tol && float64(a1.DistanceTo(b0)) <= tol
	return fwd || rev
}

// curvedCornerSurfaceViaRail routes the corner surface through the RailLoop engine and returns the
// engine-recognized analytic sphere, mirroring the planar sphereSurfaceViaRail. It is the ADR-2 Step-2
// surface-recognition seam: it falls back to `sphere` on any extraction/recognition decline or a
// non-sphere tier (do-no-harm), so a mis-extraction can never change the surface. The wired octant path
// (curvedCornerFace) keeps the EXACT-centre `sphere` for byte-identity — the engine's circumcentre-
// recovered sphere carries ~1e-12 FP noise — so this seam is validated independently now and consumed by
// the gated loop-collapse follow-up.
func curvedCornerSurfaceViaRail(w cornerWeld, arms []edgeFillet, sphere geom.Sphere, res Resolution) geom.Surface {
	loop, ok := extractCurvedCorner(w, arms, res)
	if !ok {
		return sphere
	}
	patch, ok := resolveBlend(loop, res)
	if !ok || patch.Kind != BlendKindSphere {
		return sphere
	}
	return patch.Surface
}
