// SPDX-License-Identifier: GPL-2.0-only

package ops

import (
	stdmath "math"

	"oblikovati.org/kernel/geom"
	"oblikovati.org/kernel/topo"
	"oblikovati.org/math"
)

// The EXACT rolling-ball station math of a Cylinder∧Cylinder SSI-seam fillet (OCCT blend
// simple/K2-K4, bfuseblend/B4-B5 class; reference implementation ChFi3d's cylinder-cylinder
// KPart-adjacent blends, which we reproduce as an exact-station canal per the LoftCanalStations
// discipline rather than marching).
//
// Derivation. A ball of radius r tangent to BOTH host cylinders (Aᵢ, d̂ᵢ, Rᵢ) has its centre C at
// distance r from each wall, offset to the ROLL SIDE: C = Fᵢ + σ·r·n̂ᵢ_out where Fᵢ is the contact
// foot, n̂ᵢ_out the wall's material-outward normal (exactly radial on a cylinder, sign εᵢ =
// cylinderHostRadialSign), and σ = +1 for a CONCAVE seam (ball in the reentrant void, fillet ADDS
// material) / −1 for a CONVEX seam (ball inside the material, fillet REMOVES the corner) — the
// project's roll-sense rule σ = −MAT_in·CVX. Hence C lies on BOTH coaxial OFFSET cylinders
//   ρᵢ = Rᵢ + σ·εᵢ·r,
// and the ball-centre SPINE is their intersection — the same quartic class as the seam itself.
//
// Stations are generated by AZIMUTH about the WRAP host W (the cylinder whose axis the closed seam
// loop encircles): a point of the offset cylinder O_W at azimuth φ, axial height t is
//   X(φ,t) = A_W + ρ_W·r̂(φ) + t·d̂_W,
// and the second-offset constraint dist(X, axis_O)² = ρ_O² is an EXACT QUADRATIC in t:
//   |h(φ) + t·g|² = ρ_O²,  g = d̂_W − (d̂_W·d̂_O)·d̂_O,  h(φ) = perp_O(A_W + ρ_W·r̂(φ) − A_O),
// solved per station in closed form; the two roots are the seam's two crossing branches, selected
// by axial CONTINUITY seeded at the picked rim vertex. Feet are exact radial projections
//   Fᵢ = Qᵢ + (Rᵢ/ρᵢ)·(C − Qᵢ)   (Qᵢ = the axis foot of C),
// so |C−Fᵢ| = |ρᵢ−Rᵢ| = r holds algebraically — every station column is exact on the true
// envelope; only the loft's v-interpolation between stations is approximate (bounded below).

const (
	// cylCylSeamStationsMin/Max floor and cap the ADAPTIVE station count around the closed spine —
	// the same doubling ladder the elliptic rim canal ships (fillet_elliptic_rim_canal.go): every
	// column is exact, so the count only controls the cubic v-interpolation between columns.
	cylCylSeamStationsMin = 32
	cylCylSeamStationsMax = 512
	// cylCylSeamEnvelopeCoef scales the model-relative envelope bound (1e3·res.Weld() ≈ 1e-6 of the
	// model size — four orders inside OCCT's own 1% area gate), mirroring ellipticRimEnvelopeCoef:
	// the rails are the retrim boundaries, so topological watertightness is exact by construction
	// and this bounds only the GEOMETRIC sag of the loft between exact columns.
	cylCylSeamEnvelopeCoef = 1e3
	// cylCylSeamArcSamples is the number of interior cross-section arc parameters probed per
	// mid-interval when measuring the envelope error (the two rails plus interior arc points).
	cylCylSeamArcSamples = 3
	// cylCylSeamParallelSinTol floors |d̂_W×d̂_O| — parallel-axis pairs have a LINE spine (the
	// azimuth quadratic degenerates: g = 0) and belong to the equal-parallel arm family, not here.
	cylCylSeamParallelSinTol = 1e-9 // tol:angular — sine of the axis crossing angle
)

// cylCylSeamSpine binds the exact spine to one picked seam: the wrap host W (azimuth
// parameterization), the other host O, their offset radii, and the roll side.
type cylCylSeamSpine struct {
	wrap, other geom.Cylinder
	wrapAxisE2  math.Vector3 // d̂_W × Ref_W: completes the wrap host's azimuth frame
	rhoW, rhoO  float64
	r           float64
	sigma       float64 // +1 concave (fillet adds the valley fill) / −1 convex (fillet cuts the corner)
}

// newCylCylSeamSpine derives the exact spine parameters from the picked edge's two cylinder hosts.
// ok=false — every caller then falls through to the byte-identical flat refusal (do-no-harm) — for
// a tangent/smooth edge, parallel axes (the line-spine family), an unreadable wall material sign,
// or an offset radius the fillet would consume (ρ ≤ 0).
func newCylCylSeamSpine(e *topo.Edge, wrapF, otherF *topo.Face, r float64) (cylCylSeamSpine, bool) {
	wrap := wrapF.Geometry().(geom.Cylinder)
	other := otherF.Geometry().(geom.Cylinder)
	sigma, ok := cylCylSeamRollSide(e)
	if !ok {
		return cylCylSeamSpine{}, false
	}
	cross := wrap.AxisDir.AsVector().Cross(other.AxisDir.AsVector())
	if float64(cross.Length()) < cylCylSeamParallelSinTol {
		return cylCylSeamSpine{}, false // parallel axes: a LINE spine (equal-parallel arm family), not this engine
	}
	rhoW, okW := cylCylSeamOffsetRadius(e, wrap, r, sigma)
	rhoO, okO := cylCylSeamOffsetRadius(e, other, r, sigma)
	if !okW || !okO {
		return cylCylSeamSpine{}, false
	}
	e2 := wrap.AxisDir.AsVector().Cross(wrap.Ref.AsVector())
	return cylCylSeamSpine{wrap: wrap, other: other, wrapAxisE2: e2, rhoW: rhoW, rhoO: rhoO, r: r, sigma: sigma}, true
}

// cylCylSeamRollSide maps the edge's convexity to the roll side σ: +1 for a CONCAVE seam (fused
// valley — ball in the void, both walls offset outward-material) and −1 for a CONVEX seam (cut
// corner — ball inside the material). ok=false for a tangent/smooth edge (no corner to round).
func cylCylSeamRollSide(e *topo.Edge) (float64, bool) {
	switch ClassifyEdgeConvexity(e) {
	case EdgeConcave:
		return 1, true
	case EdgeConvex:
		return -1, true
	default:
		return 0, false
	}
}

// cylCylSeamOffsetRadius is the ball-centre offset radius ρ = R + σ·ε·r of one host, ε from
// cylinderHostRadialSign (boss +1 / bore −1). ok=false when the sign is unreadable or the offset
// collapses (ρ ≤ 0: the fillet would consume the whole host wall — the rim-radius-bound class).
func cylCylSeamOffsetRadius(e *topo.Edge, cyl geom.Cylinder, r, sigma float64) (float64, bool) {
	eps, ok := cylinderHostRadialSign(e, cyl)
	if !ok {
		return 0, false
	}
	rho := cyl.Radius + sigma*eps*r
	if rho <= 0 {
		return 0, false
	}
	return rho, true
}

// wrapAzimuthAt is the azimuth φ of p about the wrap host's axis in its (Ref, d̂×Ref) frame.
func (sp cylCylSeamSpine) wrapAzimuthAt(p math.Point3) float64 {
	u := sp.wrap.Origin.VectorTo(p)
	return stdmath.Atan2(float64(u.Dot(sp.wrapAxisE2)), float64(u.Dot(sp.wrap.Ref.AsVector())))
}

// wrapAxialAt is the axial coordinate t of p along the wrap host's axis.
func (sp cylCylSeamSpine) wrapAxialAt(p math.Point3) float64 {
	return float64(sp.wrap.Origin.VectorTo(p).Dot(sp.wrap.AxisDir.AsVector()))
}

// stationAt solves the exact quadratic for the spine point at azimuth φ, taking the root nearest
// tPrev (branch continuity — the other root is the seam's second crossing loop). ok=false when the
// discriminant is negative: the offset cylinders do not meet at this azimuth, so the assumed
// closed wrap does not exist at radius r (the caller declines, naming φ).
func (sp cylCylSeamSpine) stationAt(phi, tPrev float64) (math.Point3, float64, bool) {
	dW := sp.wrap.AxisDir.AsVector()
	dO := sp.other.AxisDir.AsVector()
	rhat := sp.wrap.Ref.AsVector().Scale(math.Scalar(stdmath.Cos(phi))).Add(sp.wrapAxisE2.Scale(math.Scalar(stdmath.Sin(phi))))
	base := sp.wrap.Origin.TranslateBy(rhat.Scale(math.Scalar(sp.rhoW)))
	b := sp.other.Origin.VectorTo(base)
	h := b.Sub(dO.Scale(b.Dot(dO)))
	g := dW.Sub(dO.Scale(dW.Dot(dO)))
	t, ok := seamNearestQuadRoot(float64(g.LengthSquared()), float64(h.Dot(g)), float64(h.LengthSquared())-sp.rhoO*sp.rhoO, tPrev)
	if !ok {
		return math.Point3{}, 0, false
	}
	return base.TranslateBy(dW.Scale(math.Scalar(t))), t, true
}

// seamNearestQuadRoot solves a·t² + 2b·t + c = 0 and returns the root nearest seed. ok=false when
// the discriminant is negative (no real crossing) or the quadratic degenerates (a ≈ 0).
func seamNearestQuadRoot(a, b, c, seed float64) (float64, bool) {
	if a <= 0 {
		return 0, false // g=0 is the parallel-axis degeneracy, excluded by the spine constructor
	}
	disc := b*b - a*c
	if disc < 0 {
		return 0, false
	}
	s := stdmath.Sqrt(disc)
	t1, t2 := (-b+s)/a, (-b-s)/a
	if stdmath.Abs(t1-seed) <= stdmath.Abs(t2-seed) {
		return t1, true
	}
	return t2, true
}

// footOn projects a spine centre C radially onto one host: F = Q + (R/ρ)·(C−Q) with Q the axis
// foot, so |C−F| = |ρ−R| = r holds algebraically (the exact-station guarantee).
func cylCylSeamFootOn(cyl geom.Cylinder, rho float64, c math.Point3) math.Point3 {
	d := cyl.AxisDir.AsVector()
	u := cyl.Origin.VectorTo(c)
	q := cyl.Origin.TranslateBy(d.Scale(u.Dot(d)))
	return q.TranslateBy(q.VectorTo(c).Scale(math.Scalar(cyl.Radius / rho)))
}

// cylCylSeamStations is one resolved closed station walk: exact centres and their two exact feet,
// with station N repeating station 0 bit-identically so the lofted band closes on itself.
type cylCylSeamStations struct {
	centers, wrapFeet, otherFeet []math.Point3
}

// closedStationsAt builds n+1 stations around the closed spine starting at azimuth phi0 (the rim
// vertex azimuth, so station 0's wrap foot lands on the host's own seam ruling) walking in
// direction dir, with the LAST station re-evaluated at phi0 so it is bit-identical to the first.
// t0 seeds the branch selection at the rim vertex's own axial height. ok=false when any azimuth
// loses the crossing or the walk fails to return to its starting branch (an open/pinched spine).
func (sp cylCylSeamSpine) closedStationsAt(phi0, dir, t0 float64, n int, weld float64) (cylCylSeamStations, bool) {
	st := cylCylSeamStations{
		centers:   make([]math.Point3, n+1),
		wrapFeet:  make([]math.Point3, n+1),
		otherFeet: make([]math.Point3, n+1),
	}
	tPrev := t0
	for k := 0; k <= n; k++ {
		phi := phi0 + dir*2*stdmath.Pi*float64(k)/float64(n)
		if k == n {
			phi = phi0 // close exactly on the seam station
		}
		c, t, ok := sp.stationAt(phi, tPrev)
		if !ok {
			return cylCylSeamStations{}, false
		}
		st.centers[k], tPrev = c, t
		st.wrapFeet[k] = cylCylSeamFootOn(sp.wrap, sp.rhoW, c)
		st.otherFeet[k] = cylCylSeamFootOn(sp.other, sp.rhoO, c)
	}
	if float64(st.centers[n].DistanceTo(st.centers[0])) > weld {
		return cylCylSeamStations{}, false // the walk returned on the OTHER branch — not a closed wrap
	}
	return st, true
}

// cylCylSeamEnvelopeError is the between-station loft error the band must bound, measured at every
// interval MIDPOINT (columns are exact by construction, so the sag peaks there): how far each rail
// strays OFF its host (closed-form distance to a cylinder) and how far interior arc points stray
// from ball distance r about the exact station recovered at the probe's own azimuth.
func (sp cylCylSeamSpine) envelopeError(st cylCylSeamStations, surf geom.BSplineSurface) float64 {
	vp := spineChordParams(st.centers)
	worst := 0.0
	for j := 0; j+1 < len(st.centers); j++ {
		v := 0.5 * (vp[j] + vp[j+1])
		tSeed := sp.wrapAxialAt(st.centers[j].Midpoint(st.centers[j+1]))
		worst = stdmath.Max(worst, sp.intervalError(surf, v, tSeed))
	}
	return worst
}

// intervalError measures the rail and arc deviations at one v: rails against their hosts in closed
// form, interior arc samples against the exact station at the wrap rail's own azimuth.
func (sp cylCylSeamSpine) intervalError(surf geom.BSplineSurface, v, tSeed float64) float64 {
	qWrap := surf.PointAt(0, v)
	err := stdmath.Abs(distanceToCylinderSurface(sp.wrap, qWrap))
	qOther := surf.PointAt(1, v)
	err = stdmath.Max(err, stdmath.Abs(distanceToCylinderSurface(sp.other, qOther)))
	c, _, ok := sp.stationAt(sp.wrapAzimuthAt(qWrap), tSeed)
	if !ok {
		return stdmath.Inf(1)
	}
	for k := 1; k < cylCylSeamArcSamples; k++ {
		q := surf.PointAt(float64(k)/float64(cylCylSeamArcSamples), v)
		err = stdmath.Max(err, stdmath.Abs(float64(q.DistanceTo(c))-sp.r))
	}
	return err
}

// distanceToCylinderSurface is the signed closed-form distance of p to the cylinder wall:
// |perp(p−A)| − R (positive outside).
func distanceToCylinderSurface(cyl geom.Cylinder, p math.Point3) float64 {
	d := cyl.AxisDir.AsVector()
	u := cyl.Origin.VectorTo(p)
	perp := u.Sub(d.Scale(u.Dot(d)))
	return float64(perp.Length()) - cyl.Radius
}
