// SPDX-License-Identifier: GPL-2.0-only

package ops

import (
	"oblikovati.org/kernel/geom"
	"oblikovati.org/kernel/topo"
	"oblikovati.org/math"
)

// rulingStripFaces builds a variable fillet's blend as planar trapezoids between successive
// rulings: chord j of corner 0 pairs with chord j of corner 1 (the corners are sampled at the
// same angular stations). Adjacent rulings of the blend meet at its cone apex on the edge
// line, so each strip face is exactly planar; winding is fixed outward (away from the centre
// line) per quad. When one end is a RUN-OUT (radius 0, all its chords are the apex vertex), the
// strips collapse to a triangle fan to that apex so the cone closes manifold (not degenerate quads).
func rulingStripFaces(ef edgeFillet) []filletFace {
	cmid := ef.c0.cen.Midpoint(ef.c1.cen)
	profiles := append([]corner{ef.c0}, ef.mids...) // c0, intermediate profiles (#695), c1
	profiles = append(profiles, ef.c1)
	var out []filletFace
	for i := 0; i+1 < len(profiles); i++ {
		out = append(out, ruleStripBetween(profiles[i], profiles[i+1], cmid)...)
	}
	return out
}

// ruleStripBetween rules one strip of planar faces between two corner profiles' chord arrays. Only an
// end corner can be a run-out (collapse to an apex); intermediate profiles are always full arcs.
func ruleStripBetween(a, b corner, cmid math.Point3) []filletFace {
	out := make([]filletFace, 0, len(a.chords))
	for j := 0; j+1 < len(a.chords) && j+1 < len(b.chords); j++ {
		switch {
		case b.runout: // fan from a's arc to b's apex
			out = append(out, planarFaceFromRing([]math.Point3{a.chords[j], b.cen, a.chords[j+1]}, cmid))
		case a.runout: // fan from b's arc to a's apex
			out = append(out, planarFaceFromRing([]math.Point3{b.chords[j], a.cen, b.chords[j+1]}, cmid))
		default:
			out = append(out, planarFaceFromRing([]math.Point3{a.chords[j], b.chords[j], b.chords[j+1], a.chords[j+1]}, cmid))
		}
	}
	return out
}

// planarFaceFromRing builds one planar face over a closed point ring (a quad strip or a triangle fan
// of the cone), wound so its normal points away from the blend centre line (cmid; the wedge spans < π,
// so the sign is robust).
func planarFaceFromRing(ring []math.Point3, cmid math.Point3) filletFace {
	n := ring[0].VectorTo(ring[1]).Cross(ring[0].VectorTo(ring[len(ring)-1]))
	if n.Dot(cmid.VectorTo(centroidPts(ring))) < 0 {
		ring = reversedRing(ring)
		n = n.Scale(-1)
	}
	pl, _ := geom.NewPlane(ring[0], n)
	return filletFace{surface: pl, loops: []filletLoop{{pts: ring, curves: make([]geom.Curve3, len(ring))}}}
}

// reversedRing reverses a closed point ring while keeping its first point first (so the winding flips
// but the loop still starts at ring[0]): [p0,p1,…,pn] → [p0,pn,…,p1].
func reversedRing(ring []math.Point3) []math.Point3 {
	out := make([]math.Point3, len(ring))
	out[0] = ring[0]
	for i := 1; i < len(ring); i++ {
		out[i] = ring[len(ring)-i]
	}
	return out
}

// cylinderFace builds the rolling-ball cylinder face: tangent line on A, the rounded end at
// corner 1, tangent line on B, the rounded end at corner 0. Each end is a single arc for a
// simple/blend corner, or the seam chords for a miter corner. The loop is wound so its normal
// matches the cylinder's outward radial.
func cylinderFace(ef edgeFillet, caps map[uint64][]cornerPiece) filletFace {
	segs := []endSeg{{from: ef.c0.ta, to: ef.c1.ta}}                                 // A-tangent line c0.ta → c1.ta
	segs = append(segs, cornerEndSegs(ef.c1, caps, ef.splitEnds)...)                 // rounded end 1: c1.ta → c1.tb
	segs = append(segs, endSeg{from: ef.c1.tb, to: ef.c0.tb})                        // B-tangent line c1.tb → c0.tb
	segs = append(segs, reverseEndSegs(cornerEndSegs(ef.c0, caps, ef.splitEnds))...) // rounded end 0: c0.tb → c0.ta
	// A concave fillet's surface faces the cylinder CENTRE (material is on the far side), so its loop
	// must wind against the cylinder's outward radial — invert the convex sense.
	if cylinderSegsFlipped(ef, segs) != ef.flip {
		segs = reverseEndSegs(segs)
	}
	return filletFace{surface: ef.cyl, loops: []filletLoop{loopFromSegs(segs)}, parent: filletEdgeProvenance(ef.edge)}
}

// filletEdgeProvenance is the provenance lineage of a blend face generated by a filleted edge: the
// edge's own lineage with a "fillet:cyl" marker (ADR-0043). It derives the blend's name — and,
// through it, the names of the tangent edges where the blend meets the adjacent faces — from the
// stable identity of the filleted edge, not a build-order counter.
func filletEdgeProvenance(e *topo.Edge) topo.Lineage {
	return topo.NewLineage(append(e.Lineage().Tokens(), topo.Tok("fillet", "cyl", 0))...)
}

// endSeg is one boundary segment from→to of a cylinder loop, with the arc curve (and its
// midpoint, for re-deriving the arc when the loop is reversed) when the end is rounded by an
// arc; a miter seam's chords are straight (curve nil, arc false).
type endSeg struct {
	from, to math.Point3
	curve    geom.Curve3
	mid      math.Point3
	arc      bool
	// srcEdge is the SOURCE topo edge this segment survives from (0 = op-generated). Wave-G
	// additive: the B-spline-host retrim carries it into filletLoop.srcE so two coincident
	// survivor edges sharing both endpoints (a prism's bezier + its closing chord) keep
	// separate edge classes through the weld (#1600 method C). Zero everywhere else, so every
	// existing endSeg constructor and consumer is byte-identical.
	srcEdge uint64
}

// cornerEndSegs returns the segments rounding corner c from its ta to its tb: for a valence>3 runout
// apex the ordered far-face pieces (so the cylinder cap splits at the same points the far faces weld
// to), else the seam chords for a miter corner, otherwise a single arc through the corner's mid.
// split is edgeFillet.splitEnds — the one switch that arms the far-end multi-face cap, so the band can
// never claim a span its hosts did not adopt (fillet_farend_chain.go).
func cornerEndSegs(c corner, caps map[uint64][]cornerPiece, split bool) []endSeg {
	if split && len(c.endPieces) > 1 {
		return splitEndSegs(c)
	}
	if c.vertex != nil {
		if pieces, ok := caps[c.vertex.ID()]; ok {
			return capEndSegs(pieces)
		}
	}
	if c.miter {
		segs := make([]endSeg, 0, len(c.seam)-1)
		for i := 0; i+1 < len(c.seam); i++ {
			segs = append(segs, endSeg{from: c.seam[i], to: c.seam[i+1]})
		}
		return segs
	}
	if c.endCurve != nil {
		// The section was trimmed against a curved / oblique stop wall: the far end is the exact
		// band∩wall curve, not a section arc (fillet_farend_trim.go).
		return []endSeg{{from: c.ta, to: c.tb, curve: c.endCurve}}
	}
	arc, _ := geom.Arc3dByThreePoints(c.ta, c.mid, c.tb)
	return []endSeg{{from: c.ta, to: c.tb, curve: arc, mid: c.mid, arc: true}}
}

// reverseEndSegs reverses a chain of segments (swapping each from/to and re-deriving any arc in
// the new direction), so a forward end-rounding ta→tb can run tb→ta.
func reverseEndSegs(segs []endSeg) []endSeg {
	out := make([]endSeg, len(segs))
	for i, s := range segs {
		out[len(segs)-1-i] = reversedEndSeg(s)
	}
	return out
}

// reversedEndSeg returns ONE segment traversed backwards, with its carried curve reversed to match: an
// ARC is re-derived through its own recorded midpoint (a circumcircle through three points of a circle IS
// that circle, so this is exact), any other curve is wrapped (a canal terminal SPIRIC section has no
// by-endpoints reconstruction). The single-ball path carries only arcs and curveless straight rulings, so
// it is byte-unchanged by the wrap arm.
//
// A segment's curve MUST run from→to. discretizeEdge samples an edge's curve over its domain and then
// FORCES the polyline's two ends onto the edge's own start/end vertices, so a curve pointing the other way
// yields a polyline that leaps to the far end, walks back, and leaps again — a doubled-back boundary that
// self-crosses (simple/M4 N3 N9; planar-retrim-selfcross-report.md). Extracted from reverseEndSegs so the
// retrim splicers that may swap a bite's endpoints (matchArcFeet) reverse the curve through the same one
// primitive instead of carrying it unchanged.
func reversedEndSeg(s endSeg) endSeg {
	// srcEdge MUST survive the reversal (wave-G, #1600 method C): farPathSegs' "other way" branch
	// (fillet_curved_retrim_loop.go) runs every kept segment through this reversal, and a dropped
	// srcEdge there made a shared boundary edge un-recognizable as the SAME source edge on its two
	// bordering faces — the retrim built it TWICE as distinct op-generated (srcEdge=0) segments
	// instead of once as the shared survivor, which the assembler's edgeCatalog then welded into a
	// non-manifold multi-use edge (G5/G9: a double-bite capping face reversed one of its two far
	// paths). Every existing single-bite caller keeps srcEdge=0 either way (nothing regresses).
	r := endSeg{from: s.to, to: s.from, mid: s.mid, arc: s.arc, srcEdge: s.srcEdge}
	switch {
	case s.arc:
		// A CLOSED seam arc (full-circle rim, from==to) cannot be re-fit by three points — the
		// coincident endpoints make Arc3dByThreePoints error, its discarded zero Arc3d then reads
		// as a dead curve and collapseDeadLoop silently drops the rim, cracking the shell (P5's
		// bottom rim through the shared-face far path, W-C wave). Reverse it exactly from the
		// parent's own parameters instead.
		if arc, isArc := s.curve.(geom.Arc3d); isArc && s.from == s.to {
			r.curve = reversedWholeArc(arc)
			return r
		}
		r.curve, _ = geom.Arc3dByThreePoints(s.to, s.mid, s.from)
	case s.curve != nil:
		r.curve = geom.ReverseCurve3(s.curve)
	}
	return r
}

// reversedWholeArc reverses an Arc3d in its OWN parameters — start moved to the far end, sweep
// negated — so a closed (2π) seam keeps its exact circle through a reversal, where a three-point
// re-fit is ill-posed. PointAt(0)/PointAt(1) swap and the point set is unchanged.
func reversedWholeArc(a geom.Arc3d) geom.Arc3d {
	a.StartAngle += a.SweepAngle
	a.SweepAngle = -a.SweepAngle
	return a
}

// loopFromSegs flattens a closed chain of segments (each seg's to is the next seg's from) into a
// filletLoop: each point with the curve of the segment leaving it.
func loopFromSegs(segs []endSeg) filletLoop {
	var fl filletLoop
	for _, s := range segs {
		fl.pts = append(fl.pts, s.from)
		fl.curves = append(fl.curves, s.curve)
	}
	return fl
}

// cylinderSegsFlipped reports whether the loop winds against the cylinder's outward normal. It
// builds the test triangle from the four tangent corners (always well separated, unlike a
// miter seam's near-collinear chords), so the sign is robust for both arc and seam ends.
func cylinderSegsFlipped(ef edgeFillet, segs []endSeg) bool {
	a, b, c := ef.c0.ta, ef.c1.ta, ef.c1.tb
	n := a.VectorTo(b).Cross(a.VectorTo(c))
	u, v := ef.cyl.ParamAt(centroidPts(loopFromSegs(segs).pts))
	return n.Dot(ef.cyl.NormalAt(u, v)) < 0
}

// cornerSectionCurve is the exact cross-section trim tIn→tOut at a corner: the circular arc for
// an arc profile, or the rational conic (shoulder weight crossW) for a conic profile — the same
// geometry as the blend surface's end isoline, so the seam welds curve-for-curve (#1606).
func cornerSectionCurve(c corner, tIn, tOut math.Point3) geom.Curve3 {
	if c.endCurve != nil {
		return orientedEndCurve(c, tIn) // the band∩wall trim, oriented to the loop's traversal
	}
	if c.crossW > 0 {
		if conic, err := geom.NewConicSectionCurve(tIn, c.sh, tOut, c.crossW); err == nil {
			return conic
		}
	}
	arc, _ := geom.Arc3dByThreePoints(tIn, c.mid, tOut)
	return arc
}

// orientedEndCurve returns the corner's band∩wall trim curve running from tIn: as built when tIn is the
// A-side tangent point, reversed when the loop arrives from the B side.
func orientedEndCurve(c corner, tIn math.Point3) geom.Curve3 {
	if tIn.DistanceTo(c.ta) <= tIn.DistanceTo(c.tb) {
		return c.endCurve
	}
	return geom.ReverseCurve3(c.endCurve)
}

// ruledBlendFaces emits a variable (or conic) fillet's blend as EXACT rational ruled faces —
// one degree (2,1) NURBS span between each pair of adjacent cross-section profiles — instead of
// the C0 chord strips (#1606, audit A10). Each span's boundary reuses the profiles' exact
// section curves and the straight tangent rulings, so adjacent faces and end caps weld exactly.
func ruledBlendFaces(ef edgeFillet) []filletFace {
	profiles := append([]corner{ef.c0}, ef.mids...)
	profiles = append(profiles, ef.c1)
	out := make([]filletFace, 0, len(profiles)-1)
	for i := 0; i+1 < len(profiles); i++ {
		out = append(out, ruledBlendSpan(ef, profiles[i], profiles[i+1], i))
	}
	return out
}

// ruledBlendSpan builds one exact blend span between profiles a and b, falling back to the
// planar strip for the span only if the surface constructor rejects it (degenerate frame).
func ruledBlendSpan(ef edgeFillet, a, b corner, i int) filletFace {
	surf, err := geom.NewRuledSectionBlend(
		[3]math.Point3{a.ta, a.sh, a.tb}, [3]math.Point3{b.ta, b.sh, b.tb}, ef.secW)
	if err != nil {
		return planarFaceFromRing([]math.Point3{a.ta, b.ta, b.tb, a.tb}, a.cen.Midpoint(b.cen))
	}
	segs := blendSpanSegs(a, b)
	if blendSegsFlipped(surf, a, b) != ef.flip {
		segs = reverseEndSegs(segs)
	}
	ff := filletFace{surface: surf, loops: []filletLoop{loopFromSegs(segs)}, parent: blendSpanProvenance(ef.edge, i)}
	return ff
}

// blendSpanSegs is the span's boundary chain: A-tangent ruling, profile section at b, B-tangent
// ruling back, profile section at a reversed. A run-out profile contributes no section (its
// three points coincide at the apex), so the chain closes through the apex vertex.
func blendSpanSegs(a, b corner) []endSeg {
	segs := []endSeg{{from: a.ta, to: b.ta}}
	if !b.runout {
		segs = append(segs, endSeg{from: b.ta, to: b.tb, curve: cornerSectionCurve(b, b.ta, b.tb), mid: b.mid, arc: true})
	}
	segs = append(segs, endSeg{from: b.tb, to: a.tb})
	if !a.runout {
		segs = append(segs, endSeg{from: a.tb, to: a.ta, curve: cornerSectionCurve(a, a.tb, a.ta), mid: a.mid, arc: true})
	}
	return segs
}

// blendSegsFlipped reports whether the natural loop winding (as emitted by blendSpanSegs) runs
// against the blend's OUTWARD normal — the winding probe cylinderSegsFlipped performs for the
// constant blend, evaluated on the exact surface: outward is the surface normal at the span
// centre oriented away from the rolling-ball centre line, and the loop's winding is its Newell
// normal over the boundary corners (the wedge spans < π, so both signs are robust).
func blendSegsFlipped(surf geom.BSplineSurface, a, b corner) bool {
	n := surf.NormalAt(0.5, 0.5)
	if a.cen.Midpoint(b.cen).VectorTo(surf.PointAt(0.5, 0.5)).Dot(n) < 0 {
		n = n.Scale(-1) // outward: away from the ball centre line
	}
	ring := []math.Point3{a.ta, b.ta}
	if !b.runout {
		ring = append(ring, b.mid, b.tb)
	}
	ring = append(ring, a.tb)
	if !a.runout {
		ring = append(ring, a.mid)
	}
	return newellNormal(ring).Dot(n) < 0
}

// newellNormal is the Newell winding normal of a 3D point ring.
func newellNormal(ring []math.Point3) math.Vector3 {
	var nx, ny, nz float64
	for i := range ring {
		c, d := ring[i], ring[(i+1)%len(ring)]
		nx += float64((c.Y - d.Y) * (c.Z + d.Z))
		ny += float64((c.Z - d.Z) * (c.X + d.X))
		nz += float64((c.X - d.X) * (c.Y + d.Y))
	}
	return math.V3(math.Scalar(nx), math.Scalar(ny), math.Scalar(nz))
}

// blendSpanProvenance names an exact blend span by its generating edge and span ordinal
// (ADR-0043), mirroring filletEdgeProvenance.
func blendSpanProvenance(e *topo.Edge, i int) topo.Lineage {
	return topo.NewLineage(append(e.Lineage().Tokens(), topo.Tok("fillet", "blend", i))...)
}
