// SPDX-License-Identifier: GPL-2.0-only

package step_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"oblikovati.org/kernel/exchange"
	"oblikovati.org/kernel/exchange/step"
	"oblikovati.org/kernel/ops"
)

// The OCC oracle suite imports STEP files generated by OpenCASCADE (via gmsh) and checks the
// imported solids' total volume against OCC's exact getMass value, recorded in oracle.json.
// OCC emits the full real-world STEP vocabulary that hand-written fixtures miss — FILE_NAME
// before FILE_DESCRIPTION, SURFACE_CURVE/SEAM_CURVE edge carriers, FACE_BOUND for every bound
// (no FACE_OUTER_BOUND), rational B-spline fillets — so this is the regression guard for
// geommap/topomap completeness. testdata/occ/*.step are regenerated by
// experiments (gmsh occ.write); oracle.json holds {name: {volume, solids}}.
//
// Tolerance is on the *tessellated* volume at DefaultQuality: planar solids are near-exact;
// curved solids deviate by chord faceting (an inscribed facet polygon), so a per-shape budget
// is used rather than one loose global bound.
type oracleEntry struct {
	Volume float64 `json:"volume"`
	Solids int     `json:"solids"`
}

func TestOCCOracleVolumes(t *testing.T) {
	dir := filepath.Join("testdata", "occ")
	oracle := map[string]oracleEntry{}
	raw, err := os.ReadFile(filepath.Join(dir, "oracle.json"))
	if err != nil {
		t.Fatalf("read oracle.json: %v", err)
	}
	if err := json.Unmarshal(raw, &oracle); err != nil {
		t.Fatalf("parse oracle.json: %v", err)
	}
	if len(oracle) == 0 {
		t.Fatal("oracle.json is empty")
	}
	for name, want := range oracle {
		t.Run(name, func(t *testing.T) { checkOracle(t, dir, name, want) })
	}
}

// knownGaps are fixtures whose geommap mapping is correct but whose tessellation is not yet:
// a trimmed DOUBLY-periodic surface (an angle-limited sphere/torus) is meshed over its full
// period because periodicBandGrid handles only a single periodic direction (uPer != vPer) and
// the full-domain fallback ignores the u-trim. Tracked for the trimmed-doubly-periodic-surface
// tessellation work; the fixtures stay so the suite flips green automatically once it lands.
var knownGaps = map[string]string{
	"partial_sphere": "trimmed doubly-periodic surface tessellation (kernel/ops) not yet implemented",
	"partial_torus":  "trimmed doubly-periodic surface tessellation (kernel/ops) not yet implemented",
}

func checkOracle(t *testing.T, dir, name string, want oracleEntry) {
	if reason, gap := knownGaps[name]; gap {
		t.Skip(reason)
	}
	data, err := os.ReadFile(filepath.Join(dir, name+".step"))
	if err != nil {
		t.Fatalf("read %s.step: %v", name, err)
	}
	bodies, warns, err := step.Reader{}.ImportSolids(data, exchange.TranslationOptions{TargetUnitMM: 1})
	if err != nil {
		t.Fatalf("import %s: %v", name, err)
	}
	if len(bodies) != want.Solids {
		t.Errorf("%s: imported %d solids, want %d (warnings: %v)", name, len(bodies), want.Solids, warns)
	}
	var got float64
	for _, b := range bodies {
		if r := ops.Validate(b); !r.Valid || !b.IsSolid() {
			t.Errorf("%s: a body is not a valid solid (valid=%v solid=%v)", name, r.Valid, b.IsSolid())
		}
		got += ops.BodyGeometryProperties(b, ops.DefaultQuality()).Volume
	}
	rel := (got - want.Volume) / want.Volume
	if rel < 0 {
		rel = -rel
	}
	if rel > oracleTolerance(name) {
		t.Errorf("%s: volume %.4f vs OCC oracle %.4f (rel %.3f > %.3f); warnings: %v",
			name, got, want.Volume, rel, oracleTolerance(name), warns)
	}
}

// oracleTolerance is the allowed relative volume error for a fixture: planar-only solids are
// exact to rounding; curved solids carry chord-faceting error at DefaultQuality, more for
// doubly-curved (sphere/torus) shapes.
func oracleTolerance(name string) float64 {
	switch name {
	case "box", "wedge", "fused_boxes", "two_solids":
		return 0.001 // planar
	case "sphere", "partial_sphere", "torus", "partial_torus", "filleted_box":
		return 0.08 // doubly curved / many small blends
	default:
		return 0.05 // singly curved (cylinder, cone, drilled, boss, chamfer)
	}
}
