// SPDX-License-Identifier: GPL-2.0-only

package archguard

// toleranceDebt is the RATCHET for TestNoUnjustifiedAbsoluteEpsilons (#2189): every kernel file
// that still carries an unjustified absolute tolerance literal, and how many lines it owes.
//
// The count is what makes it a ratchet rather than a mute button. A file listed here is not
// exempt — it is capped: adding a literal to it fails the guard exactly as adding one to a clean
// file does. When a fix removes a literal the guard FAILS too, telling you to lower the number,
// so the list can only shrink and can never quietly drift out of date.
//
// Fixing an entry means one of two things: relativise the literal
// (geom.ResolutionForBox/ForSize(...).Weld()/.Plane()), or annotate it `// tol:<kind>` if it is
// genuinely dimensionless. Both are real work — do not annotate a length tolerance to clear a
// row.
//
// Baseline taken 2026-09-01: 147 files, 233 lines, against 861 kernel files. The 91 paths the
// old allowlist named are absent from this map because they are already clean; that is the
// whole point of inverting it.
var toleranceDebt = map[string]int{
	"blend/curveutil.go":                          2,
	"blend/marcher.go":                            3,
	"brep/curved_cap_crossing_corner.go":          1,
	"brep/curved_corner_junction.go":              5,
	"brep/curved_halfspace_cut_cylinder_gate.go":  1,
	"brep/curved_halfspace_cut_cylinder_side.go":  1,
	"brep/curved_halfspace_cut_cylinder_uv.go":    1,
	"brep/curved_halfspace_ruled_uv.go":           3,
	"brep/curved_halfspace_torus_uv.go":           1,
	"brep/curved_halfspace_uv_cells.go":           1,
	"brep/curved_halfspace_uv_emit.go":            5,
	"brep/curved_halfspace_uv_sample.go":          1,
	"brep/curved_halfspace_uv_trace.go":           1,
	"brep/curved_plane_partial_boss_wall.go":      1,
	"brep/curved_plane_partial_drill.go":          1,
	"brep/curved_plane_partial_gate.go":           1,
	"brep/curved_plane_uv.go":                     1,
	"brep/curved_plane_uv_frame.go":               2,
	"brep/curved_stitch.go":                       1,
	"brep/drill_multi.go":                         1,
	"exchange/drawing/units.go":                   1,
	"exchange/meshio/gltf.go":                     2,
	"exchange/meshio/weld.go":                     1,
	"exchange/step/geommap/placement.go":          1,
	"exchange/step/topomap/build_edge.go":         1,
	"exchange/step/units.go":                      4,
	"exchange/step/writer_product.go":             1,
	"fit/plane.go":                                1,
	"geom/approximate_surface.go":                 1,
	"geom/canal_edge_invert.go":                   1,
	"geom/canal_edge_march.go":                    2,
	"geom/canonical_sampling.go":                  1,
	"geom/coons_fill.go":                          1,
	"geom/curve_split_join.go":                    1,
	"geom/elliptical_cylinder.go":                 1,
	"geom/evaluator_surface.go":                   1,
	"geom/evaluator_surface_query.go":             5,
	"geom/extend_surface.go":                      1,
	"geom/first_form.go":                          1,
	"geom/fitted_bspline.go":                      1,
	"geom/intersect_cone_oblique.go":              4,
	"geom/nurbs_eval.go":                          1,
	"geom/nurbs_knots.go":                         1,
	"geom/offset_surface.go":                      1,
	"geom/plate_average_plane.go":                 3,
	"geom/project.go":                             2,
	"geom/projection_plane.go":                    1,
	"geom/resolution.go":                          2,
	"geom/spiric.go":                              1,
	"geom/transform.go":                           1,
	"hlr/project.go":                              2,
	"hlr/section.go":                              1,
	"mesh/mesh.go":                                2,
	"ops/blend/corner_provider_coons4.go":         1,
	"ops/blend/corner_provider_sphere.go":         2,
	"ops/blend/edge_convexity.go":                 1,
	"ops/blend/fillet_arc.go":                     1,
	"ops/blend/fillet_arc_endcap.go":              1,
	"ops/blend/fillet_arc_runout.go":              1,
	"ops/blend/fillet_arm_section.go":             1,
	"ops/blend/fillet_band_chart.go":              2,
	"ops/blend/fillet_band_imprint.go":            1,
	"ops/blend/fillet_bspline_host.go":            2,
	"ops/blend/fillet_bspline_host_rim.go":        1,
	"ops/blend/fillet_chain_propagate.go":         1,
	"ops/blend/fillet_chain_span_area.go":         1,
	"ops/blend/fillet_cone_far.go":                1,
	"ops/blend/fillet_corner_fullround.go":        1,
	"ops/blend/fillet_corner_radiustorus.go":      2,
	"ops/blend/fillet_corner_setback.go":          1,
	"ops/blend/fillet_corner_torus.go":            1,
	"ops/blend/fillet_curved_corner.go":           1,
	"ops/blend/fillet_curved_corner_solve.go":     1,
	"ops/blend/fillet_curved_corner_torus.go":     1,
	"ops/blend/fillet_curved_host_chart.go":       1,
	"ops/blend/fillet_curved_mixed_bspline.go":    2,
	"ops/blend/fillet_curved_rails.go":            1,
	"ops/blend/fillet_curved_retrim.go":           1,
	"ops/blend/fillet_curved_retrim_corner.go":    1,
	"ops/blend/fillet_curved_retrim_ellipse.go":   2,
	"ops/blend/fillet_curved_retrim_loop.go":      1,
	"ops/blend/fillet_cylcyl_seam.go":             2,
	"ops/blend/fillet_cylcyl_seam_weld.go":        1,
	"ops/blend/fillet_elliptic_cone_rebuild.go":   2,
	"ops/blend/fillet_elliptic_cone_spine.go":     1,
	"ops/blend/fillet_elliptic_rim_canal.go":      1,
	"ops/blend/fillet_ellipticalarm.go":           1,
	"ops/blend/fillet_face_transform.go":          1,
	"ops/blend/fillet_farend_trim.go":             1,
	"ops/blend/fillet_miter.go":                   2,
	"ops/blend/fillet_miter_asymmetric.go":        5,
	"ops/blend/fillet_miter_curved_seam.go":       1,
	"ops/blend/fillet_miter_curved_torustorus.go": 1,
	"ops/blend/fillet_miter_vertexonly.go":        3,
	"ops/blend/fillet_obstacle_dual.go":           1,
	"ops/blend/fillet_obstacle_dual_assemble.go":  1,
	"ops/blend/fillet_obstacle_panel_sliver.go":   1,
	"ops/blend/fillet_rim.go":                     1,
	"ops/blend/fillet_runout_band.go":             1,
	"ops/blend/fillet_runout_imprint.go":          1,
	"ops/blend/fillet_runout_seam.go":             1,
	"ops/blend/fillet_runout_setback.go":          1,
	"ops/blend/fillet_runout_spread.go":           4,
	"ops/blend/fillet_section_chords.go":          1,
	"ops/blend/fillet_sphere_patch.go":            2,
	"ops/blend/fillet_spiric_rim.go":              1,
	"ops/blend/fillet_spiric_rim_open.go":         1,
	"ops/blend/fillet_stripe_endface.go":          1,
	"ops/blend/fillet_stripe_junction.go":         2,
	"ops/blend/fillet_survivor_rim.go":            4,
	"ops/blend/fillet_survivor_rim_ellipse.go":    2,
	"ops/blend/fillet_torus_corner_quartic.go":    1,
	"ops/blend/fillet_twocyl_corner.go":           1,
	"ops/blend/fillet_validity.go":                3,
	"geom/quartic_real_roots.go":                  1,
	"ops/blend/tangent_chain.go":                  1,
	"ops/boolean/boolean_curved_subtract.go":      1,
	"ops/boolean/meshbool_reconstruct_merge.go":   1,
	"ops/boolean/meshbool_soup.go":                3,
	"ops/heal/snap_edges.go":                      1,
	"ops/internal/probe/probe.go":                 3,
	"ops/query/body_query.go":                     1,
	"ops/query/convexhull_seed.go":                2,
	"ops/query/identical_bodies.go":               3,
	"ops/surface/extend_edges.go":                 1,
	"ops/surface/surface_edit.go":                 5,
	"ops/tessellate/canal_band_loft.go":           1,
	"ops/tessellate/nurbs_interior.go":            2,
	"ops/tessellate/periodic_nurbs_cover.go":      1,
	"ops/tessellate/pinched_band_loft.go":         8,
	"ops/tessellate/sphere_cap_mesh.go":           1,
	"ops/tessellate/sphere_seamed_cap_mesh.go":    1,
	"ops/tessellate/sphere_zone_band_mesh.go":     2,
	"ops/tessellate/sphere_zone_mesh.go":          1,
	"ops/tessellate/spiric_band_mesh.go":          2,
	"ops/tessellate/tessellate_rectilinear.go":    1,
	"ops/tessellate/tessellate_wedge_band.go":     5,
	"ops/tessellate/union_holes.go":               1,
	"ops/tessellate/wall_seam_recut.go":           1,
	"ops/validate/fold_repair.go":                 2,
	"shading/openpbr/coat.go":                     1,
	"shading/openpbr/diffuse.go":                  1,
	"shading/openpbr/fuzz.go":                     1,
	"shading/openpbr/multiscatter.go":             1,
	"shading/openpbr/subsurface.go":               3,
	"shading/openpbr/thinfilm.go":                 1,
	"shading/openpbr/transmission.go":             1,
}
