// SPDX-License-Identifier: GPL-2.0-only

package cmdline

import (
	"sort"
	"strings"
)

// manualSection groups manual rows under a heading. The order of sections below is the
// reading order of the rendered manual; commands within a section are sorted by name.
type manualSection struct {
	title  string
	prefix string // action-id prefix that routes a command into this section
}

// manualSections is the manual's table of contents, in reading order. The longest matching
// prefix wins (so "Sketch3D." beats "Sketch."), which sectionOf relies on.
func manualSections() []manualSection {
	return []manualSection{
		{"Sketch — draw & modify", "Sketch."},
		{"Sketch — 3D", "Sketch3D."},
		{"Part — create", "Create."},
		{"Part — modify", "Modify."},
		{"Surfaces", "Surface."},
		{"Work planes", "WorkPlane."},
		{"Assembly", "Assembly."},
		{"Sheet metal", "SheetMetal."},
		{"Drawing", "Drawing."},
		{"Manage", "Manage."},
		{"View & visual styles", "View."},
		{"Mold / freeform / mesh", ""}, // Mold./Freeform./Mesh. fall here via the catch-all
	}
}

// RenderManual renders the whole vocabulary as a Markdown command manual: one table per
// section, columns Command | Aliases | Description | Example. It is deterministic (sorted),
// so a drift-guard test can compare it byte-for-byte against the committed doc.
func (v *Vocabulary) RenderManual() string {
	var b strings.Builder
	b.WriteString(manualHeader())
	bySection := v.groupBySection()
	for _, sec := range manualSections() {
		rows := bySection[sec.title]
		if len(rows) == 0 {
			continue
		}
		writeManualSection(&b, sec.title, rows)
	}
	return b.String()
}

// groupBySection buckets every manual row under its section title (longest-prefix match,
// catch-all last), each bucket sorted by canonical name.
func (v *Vocabulary) groupBySection() map[string][]Command {
	out := map[string][]Command{}
	for _, c := range v.Manual() {
		out[sectionOf(c.Action)] = append(out[sectionOf(c.Action)], c)
	}
	for _, rows := range out {
		sort.Slice(rows, func(i, j int) bool { return rows[i].Canonical < rows[j].Canonical })
	}
	return out
}

// sectionOf returns the manual section title for an action id by longest-prefix match,
// falling back to the catch-all (mold/freeform/mesh) section.
func sectionOf(action string) string {
	best, bestLen := "", -1
	for _, sec := range manualSections() {
		if sec.prefix == "" {
			continue
		}
		if strings.HasPrefix(action, sec.prefix) && len(sec.prefix) > bestLen {
			best, bestLen = sec.title, len(sec.prefix)
		}
	}
	if best == "" {
		return "Mold / freeform / mesh"
	}
	return best
}

// writeManualSection writes one Markdown table for a section.
func writeManualSection(b *strings.Builder, title string, rows []Command) {
	b.WriteString("## " + title + "\n\n")
	b.WriteString("| Command | Aliases | Description | Example |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, c := range rows {
		b.WriteString("| `" + c.Canonical + "` | " + aliasCell(c) + " | " + c.Summary + " | `" + c.Example + "` |\n")
	}
	b.WriteString("\n")
}

// aliasCell renders a command's non-canonical aliases as backticked words, or "—" when it
// has only the canonical name.
func aliasCell(c Command) string {
	if len(c.Words) < 2 {
		return "—"
	}
	quoted := make([]string, 0, len(c.Words)-1)
	for _, w := range c.Words[1:] {
		quoted = append(quoted, "`"+w+"`")
	}
	return strings.Join(quoted, ", ")
}

// manualHeader is the generated doc's preamble (it warns the file is generated).
func manualHeader() string {
	return "<!-- GENERATED by cmdline.Vocabulary.RenderManual — do not edit by hand. -->\n" +
		"<!-- Regenerate: UPDATE_MANUAL=1 go test ./app/cmdline -run TestCommandManualInSync -->\n\n" +
		"# Command manual\n\n" +
		"Every multi-letter command word the Command Window (M26) accepts, grouped by area. " +
		"The first word is the canonical name; the rest are aliases. Single-letter commands are " +
		"not listed here — they are personalised as Shift/Control chords in the keybinding editor. " +
		"This page is generated from the built-in vocabulary in " +
		"[`app/cmdline`](../../app/cmdline); a test keeps it in sync.\n\n"
}
