// SPDX-License-Identifier: GPL-2.0-only

package cmdline

import (
	"sort"
	"strings"
)

// manualCategory is one area grouping in the manual: a heading and the action-id prefixes
// whose commands fall under it. The slice order is reading order; the longest matching prefix
// wins (so "Sketch3D." beats "Sketch.").
type manualCategory struct {
	title    string
	prefixes []string
}

// manualCategories is the area table of contents shared by every manual rendering.
func manualCategories() []manualCategory {
	return []manualCategory{
		{"Sketch — draw & modify", []string{"Sketch."}},
		{"Sketch — 3D", []string{"Sketch3D."}},
		{"Part — create", []string{"Create."}},
		{"Part — modify", []string{"Modify."}},
		{"Surfaces", []string{"Surface."}},
		{"Work planes", []string{"WorkPlane."}},
		{"Mold, freeform & mesh", []string{"Mold.", "Freeform.", "Mesh."}},
		{"Sheet metal", []string{"SheetMetal."}},
		{"Assembly", []string{"Assembly."}},
		{"Drawing", []string{"Drawing."}},
		{"Manage", []string{"Manage."}},
		{"View & visual styles", []string{"View."}},
		{"Application & files", []string{"file.", "edit.", "tool.", "GetStarted."}},
	}
}

// categoryOf returns the area-category title for an action id by longest-prefix match across
// every category's prefixes, falling back to "Other" (a developer-error signal a test guards).
func categoryOf(action string) string {
	best, bestLen := "Other", -1
	for _, cat := range manualCategories() {
		for _, p := range cat.prefixes {
			if strings.HasPrefix(action, p) && len(p) > bestLen {
				best, bestLen = cat.title, len(p)
			}
		}
	}
	return best
}

// RenderManual renders the whole vocabulary as a flat, area-grouped Markdown reference: one
// table per category, columns Command | Aliases | Description | Example. Deterministic
// (sorted), so a drift-guard test compares it byte-for-byte against the committed doc.
func (v *Vocabulary) RenderManual() string {
	var b strings.Builder
	b.WriteString(flatManualHeader())
	byCat := v.groupByCategory()
	for _, cat := range manualCategories() {
		rows := byCat[cat.title]
		if len(rows) == 0 {
			continue
		}
		writeManualTable(&b, "## "+cat.title, rows)
	}
	return strings.TrimRight(b.String(), "\n") + "\n" // exactly one trailing newline (markdownlint MD012/MD047)
}

// groupByCategory buckets every manual row under its area category, each bucket sorted by
// canonical name.
func (v *Vocabulary) groupByCategory() map[string][]Command {
	out := map[string][]Command{}
	for _, c := range v.Manual() {
		out[categoryOf(c.Action)] = append(out[categoryOf(c.Action)], c)
	}
	for _, rows := range out {
		sort.Slice(rows, func(i, j int) bool { return rows[i].Canonical < rows[j].Canonical })
	}
	return out
}

// writeManualTable writes one Markdown table under the given heading.
func writeManualTable(b *strings.Builder, heading string, rows []Command) {
	b.WriteString(heading + "\n\n")
	b.WriteString("| Command | Aliases | Description | Example |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, c := range rows {
		b.WriteString("| `" + c.Canonical + "` | " + aliasCell(c) + " | " + c.Summary + " | `" + c.Example + "` |\n")
	}
	b.WriteString("\n")
}

// aliasCell renders a command's non-canonical aliases as backticked words, or "—" when it
// has only the canonical name.
func aliasCell(c Command) string {
	if len(c.Words) < 2 {
		return "—"
	}
	quoted := make([]string, 0, len(c.Words)-1)
	for _, w := range c.Words[1:] {
		quoted = append(quoted, "`"+w+"`")
	}
	return strings.Join(quoted, ", ")
}

// flatManualHeader is the in-repo reference doc's preamble (it warns the file is generated).
func flatManualHeader() string {
	return "<!-- GENERATED by cmdline.Vocabulary.RenderManual — do not edit by hand. -->\n" +
		"<!-- Regenerate: UPDATE_MANUAL=1 go test ./app/cmdline -run TestCommandManualInSync -->\n\n" +
		"# Command manual\n\n" +
		"Every multi-letter command word the Command Window (M26) accepts, grouped by area. " +
		"The first word is the canonical name; the rest are aliases. Single-letter commands are " +
		"not listed here — they are personalised as Shift/Control chords in the keybinding editor. " +
		"This page is generated from the built-in vocabulary in " +
		"[`app/cmdline`](../../app/cmdline); a test keeps it in sync.\n\n"
}
