// SPDX-License-Identifier: GPL-2.0-only

package cmdline

import "strings"

// documentGroup is the wiki manual's top level: a document type and the area categories
// (manualCategory titles) whose commands belong to it, in reading order.
type documentGroup struct {
	name       string
	categories []string
}

// documentGroups maps the manual's areas onto the document each one is used in — the wiki
// manual is grouped by document type, then by area subgroup within it.
func documentGroups() []documentGroup {
	return []documentGroup{
		{"Part", []string{
			"Sketch — draw & modify", "Sketch — 3D", "Part — create", "Part — modify",
			"Surfaces", "Work planes", "Mold, freeform & mesh",
		}},
		{"Sheet Metal Part", []string{"Sheet metal"}},
		{"Assembly", []string{"Assembly"}},
		{"Drawing", []string{"Drawing"}},
		{"All documents", []string{"Manage", "View & visual styles", "Application & files"}},
	}
}

// RenderWikiManual renders the command manual as a GitHub-wiki page grouped by document type
// (Part, Sheet Metal, Assembly, Drawing, All documents) and, within each, by area subgroup —
// one Markdown table per subgroup. It is generated from the built-in vocabulary, so a CI job
// can republish it on every merge. The output is deterministic (sorted) and self-describing.
func (v *Vocabulary) RenderWikiManual() string {
	var b strings.Builder
	b.WriteString(wikiManualHeader())
	byCat := v.groupByCategory()
	for _, dg := range documentGroups() {
		if !documentHasRows(dg, byCat) {
			continue
		}
		b.WriteString("## " + dg.name + "\n\n")
		for _, cat := range dg.categories {
			rows := byCat[cat]
			if len(rows) == 0 {
				continue
			}
			writeManualTable(&b, "### "+cat, rows)
		}
	}
	return strings.TrimRight(b.String(), "\n") + "\n" // exactly one trailing newline (markdownlint MD012/MD047)
}

// documentHasRows reports whether any of a document group's categories has commands, so an
// empty document type is skipped rather than printing a bare heading.
func documentHasRows(dg documentGroup, byCat map[string][]Command) bool {
	for _, cat := range dg.categories {
		if len(byCat[cat]) > 0 {
			return true
		}
	}
	return false
}

// wikiManualHeader is the generated wiki page's preamble.
func wikiManualHeader() string {
	return "<!-- GENERATED by cmdline.Vocabulary.RenderWikiManual — do not edit here; edit the\n" +
		"     vocabulary in app/cmdline and it republishes on merge to develop. -->\n\n" +
		"# Command Manual\n\n" +
		"Every command the Command Window accepts, grouped by document type and then by area. " +
		"Type the **Command** (or any of its **Aliases**) at the command line and follow the prompts. " +
		"Words are case-insensitive. Single-letter shortcuts are not listed here — assign them as " +
		"Shift/Control chords in the keybinding editor.\n\n"
}
